version: '2'
services:
  skyhigh-web:
    image: 'randal/skyhigh-web'
    container_name: 'skyhigh-web-instance'
    ports:
     - '8001:80'
    environment:
     - STUDENTS_SERVICE_URL=http://localhost:8181
     - SUBJECTS_SERVICE_URL=http://localhost:8182
     - ENROLLMENTS_SERVICE_URL=http://localhost:3001
  skyhigh-services-enrollment:
    image: 'randal/skyhigh-services-enrollment'
    container_name: 'skyhigh-services-enrollment-instance'
    ports:
     - '3001:3001'
    environment:
     - MONGO_HOSTNAME=mongo
     - RABBITMQ_HOSTNAME=rabbitmq
    depends_on:
     - mongo
     - rabbitmq
  skyhigh-services-students:
    image: 'randal/skyhigh-services-students'
    container_name: 'skyhigh-services-students-instance'
    ports:
     - '8181:80'
    depends_on:
     - postgres
     - rabbitmq
    environment:
     - ConnectionStrings:DefaultConnection=Host=skyhigh-students-db;Database=skyhigh-students-db;Username=randalvance;Password=P@ssw0rd
     - Endpoint:RabbitMqHostname=rabbitmq
  skyhigh-services-subjects:
    image: 'randal/skyhigh-services-subjects'
    container_name: 'skyhigh-services-subjects-instance'
    ports:
     - '8182:80'
    environment:
     - Endpoint:RabbitMqHostname=rabbitmq
    depends_on:
     - rabbitmq
  postgres:
    image: 'postgres'
    container_name: 'skyhigh-students-db'
    ports:
     - '5432:5432'
    environment:
     - POSTGRES_USER=randalvance
     - POSTGRES_PASSWORD=P@ssw0rd
     - POSTGRES_DB=skyhigh-students-db
  mongo:
    image: 'mongo'
    container_name: 'skyhigh-enrollment-mongodb'
    ports:
     - '27017:27017'
  rabbitmq:
    image: 'rabbitmq'
    container_name: 'skyhigh-rabbitmq'
    hostname: 'skyhigh-rabbitmq'
    ports:
     - '5672:5672'
     - '15672:15672'