apiVersion: v1
kind: Service
metadata:
  name: skyhigh-enrollment-service
  labels:
    app: skyhigh-enrollment-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: skyhigh-enrollment-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skyhigh-enrollment-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skyhigh-enrollment-deployment
    spec:
      containers:
      - name: skyhigh-enrollment-instance
        image: randal/skyhigh-services-enrollment
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_HOSTNAME
          value: 10.0.230.94
        - name: RABBITMQ_HOSTNAME
          value: 10.0.181.55