apiVersion: v1
kind: Service
metadata:
  name: skyhigh-rabbitmq-service
  labels:
    app: skyhigh-rabbitmq-service
spec:
  ports:
  - name: port1
    port: 5672
    protocol: TCP
  - name: port2
    port: 15672
    protocol: TCP
  selector:
    app: skyhigh-rabbitmq-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skyhigh-rabbitmq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skyhigh-rabbitmq-deployment
    spec:
      containers:
      - name: skyhigh-rabbitmq-instance
        image: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672