apiVersion: v1
kind: Service
metadata:
  name: skyhigh-students-service
  labels:
    app: skyhigh-students-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: skyhigh-students-deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skyhigh-students-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skyhigh-students-deployment
    spec:
      containers:
      - name: skyhigh-students-instance
        image: randal/skyhigh-services-students
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          value: Host=10.0.93.164;Database=skyhigh-students-db;Username=randalvance;Password=P@ssw0rd
        - name: Endpoint__RabbitMqHostname
          value: 10.0.181.55